name: Deploy to staging
on:
    push:
      brnaches:
        - "main"

jobs:
  runs-on: ubuntu-latest
  redeploy_everything:
    name: Deploying the frontend
    steps:
      - name: SSH into server
      - run:  |
          echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@98.80.79.237
          cd my-turborepo && git pull
          pnpm install
          pnpm run build
          pm2 restart web
          pm2 restart http-server
          pm2 restart websocket
