name: Deploy to staging
on:
    push:
      branches: ["main"]
       
jobs:
  
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying the frontend
    steps:
      - run:  |
          echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@98.80.79.237
          cd my-turborepo && git pull
          bun install
          bun run build
          pm2 restart web
          pm2 restart http-server
          pm2 restart websocket
